name: Create new release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Compress
        uses: vimtor/action-zip@v1.2
        with:
          files: AssemblyInfo.cs web2exe.cs LICENSE.txt run.bat
          dest: web2exe ${{ github.ref_name }}.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: web2exe ${{ github.ref_name }}.zip
